@WeatherforecastVersioningDemo_HostAddress = http://localhost:5220
### Not sure on the format for versioning either V9.9/api or api/V9.9 
GET {{WeatherforecastVersioningDemo_HostAddress}}/v1.0/api/WeatherForecast/
Accept: application/json

###
GET {{WeatherforecastVersioningDemo_HostAddress}}/v2.0/api/WeatherForecast/
Accept: application/json